repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: detect-private-key
  - id: pretty-format-json
    args: [--autofix, --indent]
  - id: trailing-whitespace
# - repo: local
#   hooks:
#   - id: rubocop
#     name: rubocop
#     description: Enforce the community Ruby Style Guide with RuboCop
#     entry: .y-kinoshita/git/hooks/rubocop.sh
#     language: script
#     pass_filenames: true
#     types: ['ruby']
#
