---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
- tmp/**/*
- public/**/*
- log/**/*
- db/**/*
- app/javascript/**/*
- app/assets/**/*
require: []
domains: []
reporters:
# - rubocop
- require_not_found
require_paths: []
plugins: []
max_files: 20000
