
[bell]
color = "#ffffff"

[cursor.style]
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(/Users/|ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = '\'
key = "^"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¬"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = "'"
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.95

[window.padding]
x = 20
y = 20

[general]
import = ["~/.alacritty-colorscheme/themes/dracula.toml"]

[terminal]
